// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: HUD_amoled_v1

#include "ui.h"

void ui_btnSetting_event_handler(lv_event_t * e)
{
	// Your code here
}

void ui_contSetting_event_handler(lv_event_t * e)
{
	// Your code here
}

void ui_btnSetL_event_handler(lv_event_t * e)
{
	// Your code here
}

void ui_btnSetR_event_handler(lv_event_t * e)
{
	// Your code here
}

void ui_btnSave_event_handler(lv_event_t * e)
{
	// Your code here
}
